USE Przejazd

DROP TABLE IF EXISTS Wykonanie_Wymiany_Akumulatora;
DROP TABLE IF EXISTS Wypozyczenie;
DROP TABLE IF EXISTS Wypozyczenie_Junk;
DROP TABLE IF EXISTS Pojazd;
DROP TABLE IF EXISTS Junk;
DROP TABLE IF EXISTS Data;
DROP TABLE IF EXISTS Czas;
DROP TABLE IF EXISTS Stacja;
DROP TABLE IF EXISTS Uzytkownik;